#!/bin/sh

set -e

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

# Copied from plymouth's hook, which skips this step when $MODULES == list
MODULES_EXCLUDE="mga r128 savage sis tdfx via panfrost"
# shellcheck disable=SC2086
copy_modules_dir kernel/drivers/gpu/drm $MODULES_EXCLUDE

# Privacy screen provider drivers, needed by drm drivers
# on systems with a builtin privacy screen.
# Reference: https://hansdegoede.livejournal.com/25948.html
manual_add_modules thinkpad_acpi

exit 0
