#!/bin/sh

set -e
set -u

# shellcheck source=tails-shell-library/libgnome-bookmarks.sh
. /usr/local/lib/tails-shell-library/libgnome-bookmarks.sh

add_gnome_bookmark "${HOME}/Tor Browser"

for launcher in Report_an_error tails-documentation ; do
    gio set "${HOME}/Desktop/${launcher}.desktop" metadata::trusted true
done
