#!/bin/sh

# Use connect-drop to open the D-Bus socket and authenticate, then
# execute tails-installer as amnesia. The "--close-from=4" causes sudo to not
# close file descriptor 3, which will be the opened D-Bus socket,
# which we want to inherit to tps-frontend.

set -eu

ENVFILE="$1"

exec /usr/local/lib/connect-drop --dbus --env-keep -- \
     sudo --close-from=4 -u amnesia \
     /usr/local/lib/run-with-env --env-file "${ENVFILE}" --delete -- \
     /usr/local/lib/tails-installer
