#!/usr/bin/python3

'''
This script is invoked before starting gnome-shell. It dumps its environment, which is often useful to
properly set the environment for many user-facing applications.

First, it save the environment in the home. Then, it asks root (with sudo) to move this environment to a
root-owned but amnesia-readable directory.

Any amnesia-capable attacker could do that. However, the privileged part will check if the file already
exists. This means that it can only be run once.
'''


import os
import sys
from pathlib import Path
import subprocess

SAVE_BIN = "/usr/local/lib/gnome-shell-save-environment"


def main():
    env_file = Path("~/.gnome-shell-environment").expanduser()
    try:
        env_file.touch(exist_ok=False)
    except FileExistsError:
        sys.exit(0)
    sys_environ = Path("/proc/%d/environ" % os.getpid())
    with sys_environ.open("rb") as buf:
        content = buf.read()
    with env_file.open("wb") as buf:
        buf.write(content)

    subprocess.check_call(["sudo", "-n", SAVE_BIN])


if __name__ == "__main__":
    main()
