#!/bin/sh

# This script is invoked before starting gnome-shell. It dumps its own
# environment for usage by other processes which need some environment
# variables set to work correctly, for example processes started via
# systemd system units don't have DBUS_SESSION_BUS_ADDRESS set.
#
# This process is run as amnesia and the environment file is writable
# by amnesia, so to avoid privilege escalation, it's important that the
# environment file is never exported in a process with more privileges
# than amnesia.

set -eu

GNOME_ENV_FILE=/run/user/1000/gnome-env

# Set some environment variables which are not set in the gnome-shell
# process but which we still need in some processes which export the
# environment file.
if [ -z "${DISPLAY:-}" ]; then
  export DISPLAY=:0
fi

if [ -z "${XAUTHORITY:-}" ]; then
  for xauth in /run/user/1000/.mutter-Xwaylandauth.*; do
    export XAUTHORITY="${xauth}"
  done
fi

if [ -z "${WAYLAND_DISPLAY:-}" ]; then
  for wayland_display in /run/user/1000/wayland-*; do
    export WAYLAND_DISPLAY="${wayland_display}"
  done
fi

# To avoid issues with environment variables that contain newlines, we
# dump the environment null-terminated
env --null > "${GNOME_ENV_FILE}"
