#!/usr/bin/env python3

# This script exports environment variables from the file specified in
# the ENVFILE argument and then executes the specified command.
#
# If any environment variables from ENVFILE are already set in the
# current environment, those are *not* overwritten, so environment
# variables set by the caller take precedence over the ones from ENVFILE.
#
# ENVFILE must be null-terminated.

import os
import sys
from pathlib import Path

usage = f"{sys.argv[0]} ENVFILE [--] COMMAND [ARG...]"


def read_envfile(envfile: str) -> dict:
    env = dict(os.environ)
    for line in Path(envfile).read_text().split('\0'):
        if not line:
            continue
        key, value = line.split("=", 1)
        if key not in env:
            env[key] = value
    return env


def main():
    if os.geteuid() != 1000:
        print(f"{sys.argv[0]: This script must be run as amnesia}", file=sys.stderr)
        sys.exit(1)

    if len(sys.argv) < 3:
        print(usage, file=sys.stderr)
        sys.exit(1)

    if sys.argv[2] == "--":
        del sys.argv[2]

    env = read_envfile(sys.argv[1])
    file = sys.argv[2]
    args = sys.argv[2:]
    os.execvpe(file, args, env=env)


if __name__ == "__main__":
    main()
