#!/bin/sh

set -eu

CONF_FILE=/live/persistence/TailsData_unlocked/persistence.conf

[ -w "$CONF_FILE" ] || exit 1

if ! grep -E --line-regexp -qs '/var/lib/tca\s+source=tca' "$CONF_FILE"; then
    echo '/var/lib/tca source=tca' >> "$CONF_FILE"
fi
