#!/usr/bin/env python3

import dbus
from pathlib import Path
import subprocess

PID_FILE="/run/user/1000/.dbus-proxy/a11y-bus-proxy.pid"
SOCKET_FILE="/run/user/1000/.dbus-proxy/a11y-bus-proxy.sock"


def main():
    Path(PID_FILE).parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    Path(SOCKET_FILE).parent.mkdir(mode=0o700, parents=True, exist_ok=True)

    bus = dbus.SessionBus()
    obj = bus.get_object("org.a11y.Bus", "/org/a11y/bus")
    iface = dbus.Interface(obj, dbus_interface="org.a11y.Bus")
    address = str(iface.GetAddress())
    subprocess.run(["/usr/local/lib/tails-dbus-proxy", "--pid-file", PID_FILE,
                    address, SOCKET_FILE])


if __name__ == "__main__":
    main()
