#!/bin/sh

set -eu
set -x

needs_to_sync() {
    mountpoint -q /media/tails-persistence-setup/TailsData \
        && ! [ -d /media/tails-persistence-setup/TailsData/apt ]
}

if needs_to_sync; then
    echo "Copy APT data to newly created Persistent Storage"
    touch /media/tails-persistence-setup/TailsData/apt_sync_started
    mkdir /media/tails-persistence-setup/TailsData/apt/
    cp -a /var/cache/apt/archives \
       /media/tails-persistence-setup/TailsData/apt/cache
    cp -a /var/lib/apt/lists \
       /media/tails-persistence-setup/TailsData/apt/
    touch /media/tails-persistence-setup/TailsData/apt_sync_completed
    sync --file-system /media/tails-persistence-setup/TailsData/apt
else
    echo "No need to copy APT data to newly created Persistent Storage"
fi
