#!/usr/bin/python3

import json
import datetime
import logging
import locale
import os
import sys
import zoneinfo


def normalize_tzname(tzname):
    '''
    Tor Connection stores some tz in non-standard way.

    This helps us avoid problem when this appears.
    '''
    if tzname is None:
        return None
    if tzname.startswith('UTC'):
        tzname = None
    return tzname


def get_tz(tzname):
    return zoneinfo.ZoneInfo(tzname)


def tzname_is_valid(tzname):
    try:
        get_tz(tzname)
    except Exception as exc:
        logging.warning("tzname is not valid: %s", str(exc))
        return False
    return True


def main():
    if os.getuid() != 0:
        print("Only root can run this!", file=sys.stderr)
        sys.exit(1)

    if 'LC_TIME' in os.environ:
        try:
            locale.setlocale(locale.LC_TIME, os.environ['LC_TIME'])
        except locale.Error:
            logging.warning('Invalid timezone specified: %s', os.environ['LC_TIME'])

    try:
        tca_state = json.load(open('/run/tca/tca.state'))
    except:
        tzname = None
    else:
        tzname = tca_state.get('ui', {}).get('time', {}).get('tz', None)

    tzname = normalize_tzname(tzname)

    # This is the default date format used by GNOME's clock. Note that
    # there are dconf settings for making it show seconds etc that we
    # don't support.
    date_format = '%a %b %-e  %R'
    if tzname and tzname_is_valid(tzname):
        now = datetime.datetime.now(tz=get_tz(tzname))
        print(now.strftime(date_format))
    else:
        now = datetime.datetime.now()
        print(now.strftime(date_format), 'GMT')


if __name__ == '__main__':
    main()
