#!/usr/bin/python3

import json
import datetime
import logging
import locale
import os
import sys


def main():
    if os.getuid() != 0:
        print("Only root can run this!", file=sys.stderr)
        sys.exit(1)

    if 'LC_TIME' in os.environ:
        try:
            locale.setlocale(locale.LC_TIME, os.environ['LC_TIME'])
        except locale.Error:
            logging.warning('Invalid timezone specificied: %s', os.environ['LC_TIME'])

    try:
        tca_state = json.load(open('/run/tca/tca.state'))
    except:
        tzname = None
    else:
        tzname = tca_state.get('ui', {}).get('time', {}).get('tz', None)

    if tzname:
        env = {'TZ': tzname}
        env.update(os.environ)
        os.execve('/bin/date', ['date'], env=env)
    else:
        now = datetime.datetime.now()
        print(now.strftime('%c'), 'GMT')

    



if __name__ == '__main__':
    main()
