#!/bin/sh

set -eu
set -x

needs_to_sync() {
    mountpoint -q /live/persistence/TailsData_unlocked                   \
        && ! mountpoint -q /var/lib/tca                                  \
        && test -e /live/persistence/TailsData_unlocked/persistence.conf \
        && grep -E --line-regexp -qs                                     \
                '/var/lib/tca\s+source=tca'                              \
                /live/persistence/TailsData_unlocked/persistence.conf
}

if needs_to_sync; then
    echo "Copying Tor configuration to Persistent Storage"

    # Clean up potential leftovers of previously disabled "Tor
    # Bridges" persistence feature (#8447)
    rm -rf /live/persistence/TailsData_unlocked/tca

    cp -a /var/lib/tca /live/persistence/TailsData_unlocked/
    sync --file-system /live/persistence/TailsData_unlocked/tca
else
    echo "No need to copy Tor configuration to Persistent Storage"
fi
