#!/bin/sh

set -e
set -u

# shellcheck source=../../../tails-shell-library/libgnome-bookmarks.sh
. /usr/local/lib/tails-shell-library/libgnome-bookmarks.sh

PERSISTENT_DIR='/home/amnesia/Persistent'
TOR_BROWSER_PERSISTENT_DIR='/home/amnesia/Persistent/Tor Browser'
add_gnome_bookmark "${PERSISTENT_DIR}"
add_gnome_bookmark "${TOR_BROWSER_PERSISTENT_DIR}" "Tor Browser (persistent)"
