#!/bin/sh

set -e
set -u

PERSISTENT_DIR='/home/amnesia/Persistent'
TOR_BROWSER_PERSISTENT_DIR='/home/amnesia/Persistent/Tor Browser'
sudo -u amnesia /usr/local/lib/add-GNOME-bookmark "${PERSISTENT_DIR}"
sudo -u amnesia /usr/local/lib/add-GNOME-bookmark \
     "${TOR_BROWSER_PERSISTENT_DIR}" "Tor Browser (persistent)"
