#!/bin/sh

set -e
set -u

NOSYMFOLLOW_MOUNTPOINT='/var/lib/tails-persistent-storage/nosymfollow'
TARGET="${NOSYMFOLLOW_MOUNTPOINT}/home/amnesia/Persistent/Tor Browser"
install -d -o amnesia -g amnesia -m 0700 "${TARGET}"
