#!/bin/sh

set -e
set -u

NOSYMFOLLOW_MOUNTPOINT='/run/nosymfollow'
PERSISTENT_DIR="${NOSYMFOLLOW_MOUNTPOINT}/home/amnesia/Persistent"
if [ -e "${PERSISTENT_DIR}" ]; then
  rmdir "${PERSISTENT_DIR}"
fi
