#!/bin/sh

set -e

echo "Replacing swapon executable"

# Only allow setting up swap for zram devices.
# Rationale: security-in-depth model.

# Move any /sbin/swapon installed by any package out of the way,
# now (--rename) as well for any future one (hint: apt-get upgrade...).
dpkg-divert --rename --add /sbin/swapon

ln -s /sbin/swapon.tails /sbin/swapon
