#!/bin/sh

set -e

echo "Replacing swapon executable"

# Only allow setting up swap for zram devices.
# Rationale: security-in-depth model.

SWAPON=/sbin/swapon

# Move any /sbin/swapon installed by any package out of the way,
# now (--rename) as well for any future one (hint: apt-get upgrade...).
dpkg-divert --rename --add /sbin/swapon

cat > $SWAPON << 'EOF'
#!/bin/sh

set -eu

for param in "$@"; do
  if echo "${param}" | grep -v /dev/zram | grep -q /dev; then
    echo >&2 "Setting up swap is only allowed for zram devices"
    exit 1
  fi
done

/sbin/swapon.distrib "$@"
EOF
chmod 755 $SWAPON
