#!/bin/sh

set -e
set -u

echo "Creating tor's ClientOnionAuthDir"

# If this directory doesn't exist, tor will refuse to start
install --directory /var/lib/tor/keys \
        --owner=debian-tor --group=debian-tor --mode=700
