#!/bin/sh

set -e

# Append some version information to /etc/tails/version

echo "Appending some version information to /etc/tails/version"

echo "live-boot: $(dpkg-query -W -f='${Version}\n' live-boot)" \
   >> /etc/tails/version

echo "live-config: $(dpkg-query -W -f='${Version}\n' live-config)" \
   >> /etc/tails/version
