#!/bin/sh

set -eu
set -x

option="$(tr ' ' '\n' < /proc/cmdline | grep '^early_patch\b')"

[ -n "$option" ] || exit 0

for mod in fscache 9pnet 9pnet_virtio 9p; do
    modprobe -vvv -d /root/ $mod
done

mountpoint=/root/mnt
mkdir -p "$mountpoint"
mount -t 9p src "$mountpoint"
if [ -x "${mountpoint}/hook" ]
then
    "${mountpoint}/hook" /root
fi
