#!/bin/sh

set -x

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
	prereqs)
	prereqs
	exit 0
	;;
esac

set -eu

option="$(tr ' ' '\n' < /proc/cmdline | grep '^early_patch\b')"

[ -n "$option" ] || exit 0

for mod in fscache 9pnet 9pnet_virtio 9p; do
    modprobe -vvv -d /root/ $mod
done

mountpoint=/root/mnt
mkdir -p "$mountpoint"
mount -t 9p src "$mountpoint"

# early_patch=test-suite runs a different hook
if echo "$option" | grep -qw test-suite; then
    hook="${mountpoint}/hook-test-suite"
else
    hook="${mountpoint}/hook"
fi
if [ -x "${hook}" ]; then
    "${hook}" /root || true
fi

# early_patch=umount will umount the filesystem immediately after running the hook
# this is needed to have early_patch in the test suite.
# In fact, qemu cannot do snapshots while this is mounted
if echo "$option" | grep -qw umount
then
    umount "$mountpoint"
fi
