#!/bin/sh

set -e
set -u

# shellcheck source=../../../tails-shell-library/libgnome-bookmarks.sh
. /usr/local/lib/tails-shell-library/libgnome-bookmarks.sh

DOTFILES_SOURCE_DIR='/live/persistence/TailsData_unlocked/dotfiles'
add_gnome_bookmark "$DOTFILES_SOURCE_DIR" "Dotfiles"
